### ISSUE TITLE
Add a README.md

### ISSUE THREAD

**Issue by IsuruDilhan** [IsuruDilhan/X-MediaPlayer#3]

**Comment by josenildoamorim** [comment]
on it. do you want any special information on the readme? instructions on how to use, install? give me a hint :)

**Comment by IsuruDilhan** [comment]
Great ! Nah, Its just a set of Js and Css.  Player.html will open up the player. Enhancements are also welcome.  😊

**Comment by josenildoamorim** [comment]
Allright ! Did a pull request :) if you need more, just tell me and ill do!

**Comment by IsuruDilhan** [comment]
This one looks great! Thanks for the PR. :)
